/**
 * `goli init` — Initialize GOLI.md project memory and build the index.
 *
 * Creates:
 * - `GOLI.md` in the repo root (the canonical project context every
 *   agent reads before starting work — architecture overview, coding
 *   standards, forbidden files)
 * - `.goli-cli/` directory for per-project state
 * - Tree-sitter index of the codebase (Phase 7)
 *
 * @module commands/init
 */

import { existsSync, writeFileSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

import { loadConfig } from '@goli-cli/config';
import { APP_VERSION } from '@goli-cli/shared/utils/constants.js';
import { configureLogger, defaultLifecycleLogPath } from '@goli-cli/shared/utils/logger.js';

const GOLI_MD_TEMPLATE = `# GOLI.md — Project Memory

> This file is the **canonical project context** that every GOLI-CLI agent
> reads before starting work. Edit it to reflect your project's architecture,
> coding standards, and forbidden files.

## Architecture Overview

<!-- Describe your project's high-level architecture here. -->
<!-- Example: "This is a Next.js 16 monorepo with a Postgres database..." -->

## Coding Standards

<!-- List your project's coding conventions. -->
<!-- Example: -->
<!-- - Use TypeScript strict mode -->
<!-- - Use named exports (no default exports) -->
<!-- - Use ESM imports with .js extensions -->
<!-- - 2-space indentation, single quotes, semicolons -->

## Forbidden Files

<!-- List files/paths the agent must NEVER modify. -->
<!-- Example: -->
<!-- - .env (contains real API keys) -->
<!-- - dist/ (build output) -->
<!-- - node_modules/ (dependencies) -->
<!-- - package-lock.json (pinned dep graph) -->

## Build & Test Commands

<!-- List the commands to build, test, lint, etc. -->
<!-- Example: -->
<!-- - Build: \`npm run build\` -->
<!-- - Test:  \`npm test\` -->
<!-- - Lint:  \`npm run lint\` -->

## Agent Notes

<!-- Anything else the agent should know? -->
<!-- - Known gotchas -->
<!-- - Preferred libraries -->
<!-- - Architecture decisions (link to ADRs) -->

---
Generated by \`goli init\` (GOLI-CLI v${'$'}{APP_VERSION}).
Edit this file to teach GOLI-CLI about your project.
`;

/**
 *
 */
export async function runInit(): Promise<number> {
  loadConfig();
  configureLogger({
    level: 'silent',
    lifecycleLogPath: defaultLifecycleLogPath(),
  });

  process.stdout.write('\n');
  process.stdout.write('🚀 GOLI-CLI Init — Initialize Project Memory\n');
  process.stdout.write('═'.repeat(60) + '\n\n');

  const goliMdPath = join(process.cwd(), 'GOLI.md');
  const goliCliDir = join(process.cwd(), '.goli-cli');

  let created = 0;

  // ─── GOLI.md ─────────────────────────────────────────────────
  if (existsSync(goliMdPath)) {
    process.stdout.write('  ℹ️  GOLI.md already exists — leaving it as-is.\n');
  } else {
    writeFileSync(goliMdPath, GOLI_MD_TEMPLATE.replace('${APP_VERSION}', APP_VERSION));
    process.stdout.write('  ✓ Created GOLI.md (project memory)\n');
    created++;
  }

  // ─── .goli-cli/ directory ────────────────────────────────────
  if (!existsSync(goliCliDir)) {
    mkdirSync(goliCliDir, { recursive: true });
    process.stdout.write('  ✓ Created .goli-cli/ directory\n');
    created++;
  } else {
    process.stdout.write('  ℹ️  .goli-cli/ already exists.\n');
  }

  // ─── Tree-sitter index (Phase 7) ─────────────────────────────
  process.stdout.write('  ⏳ Tree-sitter index build lands in Phase 7 (Context Engine).\n');

  // ─── Summary ─────────────────────────────────────────────────
  process.stdout.write('\n' + '─'.repeat(60) + '\n');
  if (created > 0) {
    process.stdout.write(`✓ Initialization complete (${created} file(s) created).\n`);
    process.stdout.write('  Edit GOLI.md to teach GOLI-CLI about your project.\n');
  } else {
    process.stdout.write('✓ Already initialized. No changes made.\n');
  }
  process.stdout.write('\n');

  return 0;
}
