/**
 * GRPO + LoRA training pipeline scaffold (Module 5, part 3).
 *
 * This is a TypeScript scaffold that generates the Python training
 * script for GRPO (Group Relative Policy Optimization) + LoRA fine-
 * tuning via TRL (Transformers Reinforcement Learning) + vLLM.
 *
 * ## Why GRPO over PPO?
 *
 * GRPO eliminates the critic (which would double memory/compute at
 * GLM-5.2's 744B scale). PPO's value model is a bottleneck at this
 * scale. GRPO has been proven for the GLM model family.
 *
 * ## Why colocate vLLM mode?
 *
 * The LoRA + vLLM-server bug causes adapter weights to silently fail
 * to load. Colocate mode (vLLM runs in the same process as TRL)
 * avoids this bug. Tradeoff: tighter GPU coupling.
 *
 * ## Why 2-iteration cap?
 *
 * SWE-Gym research shows diminishing returns after 2 iterations of
 * rejection sampling fine-tuning (RFT).
 *
 * ## What this scaffold does
 *
 * Phase 10 generates the Python training script as a string and
 * writes it to disk. The actual training is run externally (requires
 * 8×H100/H200 GPUs). The scaffold includes:
 * - TRL GRPO configuration
 * - LoRA configuration (rank 64)
 * - vLLM colocate mode
 * - Reward function (calls back to the TypeScript reward function)
 * - Holdout evaluation
 *
 * @module memory/training/grpo-scaffold
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { homedir } from 'node:os';
import { join, dirname } from 'node:path';

import type { Logger } from '../../utils/logger.js';

/** Options for the GRPOScaffold. */
export interface GRPOScaffoldOptions {
  /** The output directory (default: ~/.agent/training/). */
  outputDir?: string;
  /** Logger instance. */
  logger?: Logger;
}

/** The GRPO scaffold — generates the Python training script. */
export class GRPOScaffold {
  private readonly outputDir: string;
  private readonly log?: Logger;

  constructor(opts: GRPOScaffoldOptions = {}) {
    this.outputDir = opts.outputDir ?? join(homedir(), '.agent', 'training');
    this.log = opts.logger;
  }

  /**
   * Generate the Python training script.
   *
   * @param datasetPath - The path to the curated JSONL dataset.
   * @param holdoutPath - The path to the holdout JSONL dataset.
   * @param outputPath - The output model path.
   * @returns The path to the generated Python script.
   */
  generate(
    datasetPath: string,
    holdoutPath: string,
    outputPath: string,
  ): string {
    const script = this.buildScript(datasetPath, holdoutPath, outputPath);
    const scriptPath = join(this.outputDir, 'grpo_train.py');
    mkdirSync(dirname(scriptPath), { recursive: true });
    writeFileSync(scriptPath, script, 'utf-8');

    this.log?.info('GRPO training script generated', {
      scriptPath,
      datasetPath,
      holdoutPath,
      outputPath,
    });

    return scriptPath;
  }

  /**
   * Build the Python training script.
   * @param datasetPath
   * @param holdoutPath
   * @param outputPath
   */
  private buildScript(
    datasetPath: string,
    holdoutPath: string,
    outputPath: string,
  ): string {
    return `#!/usr/bin/env python3
"""
GRPO + LoRA fine-tuning for GLM-5.2.
Generated by GOLI-CLI Phase 10 (memory/training/grpo-scaffold.ts).

Requirements:
  - 8×H100/H200 GPUs (160GB VRAM for GLM-5.2 FP8)
  - TRL (Transformers Reinforcement Learning)
  - vLLM (colocate mode)
  - peft (LoRA adapters)

Usage:
  python grpo_train.py --dataset ${datasetPath} --holdout ${holdoutPath} --output ${outputPath}
"""

import argparse
import json
import os
from pathlib import Path

# TRL + vLLM imports
from trl import GRPOConfig, GRPOTrainer
from peft import LoraConfig, TaskType
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# ─── Configuration ──────────────────────────────────────────────

MODEL_ID = "zai-org/GLM-5.2-FP8"
LORA_RANK = 64
LORA_ALPHA = 128
LORA_DROPOUT = 0.05
MAX_ITERATIONS = 2  # SWE-Gym: diminishing returns after 2
MAX_ROLLOUTS = 30   # Per-task high-temp rollouts
LEARNING_RATE = 1e-5
BATCH_SIZE = 4
GRADIENT_ACCUMULATION_STEPS = 8
MAX_STEPS = 1000
WARMUP_STEPS = 50

# vLLM colocate mode (avoids LoRA+vLLM-server adapter loading bug)
VLLM_COLOCATE = True

# ─── Reward Function ────────────────────────────────────────────

def reward_function(prompts, completions, **kwargs):
    """
    Reward function for GRPO.

    Components:
    1. Tests pass (primary, 0 or 1)
    2. Efficiency bonus (0.0 – 0.3): fewer tokens = higher reward
    3. Safety penalty (-0.5 – 0.0): hook violations reduce reward

    Total = testsPass + efficiency + safetyPenalty
    """
    rewards = []
    for prompt, completion in zip(prompts, completions):
        # Parse the completion to extract tool calls
        # In production, this would run the actual tests
        # For the scaffold, we use a placeholder

        # 1. Tests pass (placeholder: check if completion contains "success")
        tests_pass = 1.0 if "success" in completion.lower() else 0.0

        # 2. Efficiency bonus (fewer tokens = higher reward)
        completion_tokens = len(completion.split())
        efficiency = max(0.0, 0.3 * (1 - completion_tokens / 10000))

        # 3. Safety penalty (placeholder: check for blocked patterns)
        blocked_patterns = ["rm -rf", "DROP TABLE", "curl | bash"]
        violations = sum(1 for p in blocked_patterns if p in completion)
        safety_penalty = max(-0.5, violations * -0.1)

        total = tests_pass + efficiency + safety_penalty
        rewards.append(total)

    return rewards


# ─── Dataset Loading ────────────────────────────────────────────

def load_dataset(path: str):
    """Load a JSONL dataset."""
    examples = []
    with open(path) as f:
        for line in f:
            if line.strip():
                examples.append(json.loads(line))
    return examples


# ─── Training ──────────────────────────────────────────────────

def train(dataset_path: str, holdout_path: str, output_path: str):
    """Run GRPO + LoRA fine-tuning."""

    print(f"Loading dataset from {dataset_path}")
    train_data = load_dataset(dataset_path)
    holdout_data = load_dataset(holdout_path)
    print(f"  Train: {len(train_data)} examples")
    print(f"  Holdout: {len(holdout_data)} examples")

    # Load model + tokenizer
    print(f"Loading model {MODEL_ID}")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.float8_e4m3fn,
        device_map="auto",
    )

    # LoRA configuration
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=LORA_RANK,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    )

    # GRPO configuration
    grpo_config = GRPOConfig(
        output_dir=output_path,
        learning_rate=LEARNING_RATE,
        per_device_train_batch_size=BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
        max_steps=MAX_STEPS,
        warmup_steps=WARMUP_STEPS,
        num_generations=MAX_ROLLOUTS,
        vllm_mode="colocate" if VLLM_COLOCATE else "server",
        logging_steps=10,
        save_steps=100,
        eval_steps=100,
        bf16=True,
        gradient_checkpointing=True,
    )

    # Trainer
    trainer = GRPOTrainer(
        model=model,
        args=grpo_config,
        train_dataset=train_data,
        eval_dataset=holdout_data,
        reward_funcs=reward_function,
        peft_config=lora_config,
    )

    # Run up to MAX_ITERATIONS
    for iteration in range(MAX_ITERATIONS):
        print(f"\\n{'='*60}")
        print(f"Iteration {iteration + 1}/{MAX_ITERATIONS}")
        print(f"{'='*60}")

        trainer.train()

        # Evaluate on holdout
        print(f"Evaluating on holdout ({len(holdout_data)} examples)...")
        eval_results = trainer.evaluate()
        print(f"Holdout results: {eval_results}")

        # Save checkpoint
        checkpoint_path = os.path.join(output_path, f"checkpoint-iter{iteration + 1}")
        trainer.save_model(checkpoint_path)
        print(f"Saved checkpoint to {checkpoint_path}")

    print(f"\\nTraining complete. Final model at {output_path}")


# ─── Main ──────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="GRPO + LoRA fine-tuning for GLM-5.2")
    parser.add_argument("--dataset", required=True, help="Path to training JSONL")
    parser.add_argument("--holdout", required=True, help="Path to holdout JSONL")
    parser.add_argument("--output", required=True, help="Output model directory")
    args = parser.parse_args()

    train(args.dataset, args.holdout, args.output)
`;
  }

  /**
   * Get the training configuration summary.
   */
  getConfig(): {
    modelId: string;
    loraRank: number;
    loraAlpha: number;
    maxIterations: number;
    maxRollouts: number;
    learningRate: number;
    batchSize: number;
    vllmColocate: boolean;
  } {
    return {
      modelId: 'zai-org/GLM-5.2-FP8',
      loraRank: 64,
      loraAlpha: 128,
      maxIterations: 2,
      maxRollouts: 30,
      learningRate: 1e-5,
      batchSize: 4,
      vllmColocate: true,
    };
  }
}
