/**
 * scripts/gen-completions.ts
 *
 * A3 acceptance criterion: every public CLI flag has a shell completion.
 *
 * Generates shell completion scripts for bash, zsh, and fish that cover
 * all `goli` subcommands and their flags. The completions are derived
 * from the Commander program definition (single source of truth).
 *
 * Output:
 *   completions/goli.bash  — bash completion script
 *   completions/goli.zsh   — zsh completion script
 *   completions/goli.fish  — fish completion script
 *
 * Usage:
 *   npx tsx scripts/gen-completions.ts
 *
 * Install (bash):
 *   source completions/goli.bash
 *   # or copy to /etc/bash_completion.d/goli
 *
 * Install (zsh):
 *   fpath+=(~/.zsh/completions)
 *   cp completions/_goli ~/.zsh/completions/
 *   compinit
 *
 * Install (fish):
 *   cp completions/goli.fish ~/.config/fish/completions/
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const REPO_ROOT = resolve(import.meta.dirname, '..');
const OUTPUT_DIR = resolve(REPO_ROOT, 'apps/cli/completions');

// ─── Command/flag spec (mirrors apps/cli/src/index.ts createProgram) ─

interface FlagSpec {
  short?: string;
  long: string;
  takesArg: boolean;
  description: string;
}

interface CommandSpec {
  name: string;
  args?: string;
  description: string;
  flags: FlagSpec[];
}

const GLOBAL_FLAGS: FlagSpec[] = [
  { short: '-V', long: '--version', takesArg: false, description: 'Print version and exit' },
  { short: '-p', long: '--print', takesArg: true, description: 'Headless mode: run the agent, print the result to stdout, exit' },
  { long: '--debug', takesArg: false, description: 'Enable debug logging' },
  { long: '--model', takesArg: true, description: 'Override the default model for this session' },
  { long: '--god', takesArg: false, description: 'Bypass ALL safety gates (USE WITH EXTREME CAUTION)' },
  { long: '--auto', takesArg: false, description: 'Auto-approve Tier 2 (Risky) actions' },
  { long: '--sandbox', takesArg: true, description: 'Override sandbox mode: read-only | workspace-write | danger-full-access' },
  { long: '--effort', takesArg: true, description: 'Override reasoning effort: low | high | max' },
  { long: '--output-format', takesArg: true, description: 'Headless output format: text | json | stream-json (default: text)' },
  { long: '--spec-mode', takesArg: false, description: 'Enable spec-driven mode — edit_file/write_file require an approved spec (H13)' },
  { long: '--diff-review', takesArg: false, description: 'Enable diff-first review in headless mode (H14)' },
  { long: '--resume', takesArg: true, description: 'Resume a previous session by ID (H16)' },
  { long: '--branch', takesArg: true, description: 'Branch a previous session by ID into a new session (H16)' },
  { long: '--local-llms', takesArg: false, description: 'Local-LLM three-axis router across local Ollama workers + cloud tier' },
  { short: '-h', long: '--help', takesArg: false, description: 'Print this help and exit' },
];

const COMMANDS: CommandSpec[] = [
  {
    name: 'wakeup',
    args: '[prompt]',
    description: 'Wake up the 11-agent swarm to perform a task',
    flags: [
      { short: '-i', long: '--interactive', takesArg: false, description: 'Start the full Ink TUI for real-time chat (Phase 3)' },
    ],
  },
  {
    name: 'doctor',
    description: 'Check system requirements and environment health',
    flags: [],
  },
  {
    name: 'status',
    description: 'Show health dashboard and active session stats',
    flags: [],
  },
  {
    name: 'audit',
    description: 'Verify safety audit log integrity',
    flags: [
      { short: '-v', long: '--verbose', takesArg: false, description: 'Show recent entries' },
      { long: '--json', takesArg: false, description: 'Output as JSON (for CI / scripts)' },
    ],
  },
  {
    name: 'usage',
    description: 'Show model usage and cost breakdown',
    flags: [],
  },
  {
    name: 'commit',
    description: 'Apply pending changes from a session to your host',
    flags: [],
  },
  {
    name: 'init',
    description: 'Initialize GOLI.md project memory and build the index',
    flags: [],
  },
  {
    name: 'mcp',
    description: 'Manage MCP (Model Context Protocol) servers',
    flags: [],
  },
];

// ─── Bash completion ──────────────────────────────────────────────────

function genBash(): string {
  const lines: string[] = [
    '# goli bash completion',
    '# Generated by scripts/gen-completions.ts — do not edit by hand.',
    '# Install: source this file in your .bashrc, or copy to /etc/bash_completion.d/goli',
    '',
    '_goli() {',
    '    local cur prev opts cmds',
    '    COMPREPLY=()',
    '    cur="${COMP_WORDS[COMP_CWORD]}"',
    '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
    '',
    '    # Top-level commands',
    '    cmds="wakeup doctor status audit usage commit init mcp help"',
    '',
    '    # If completing the first word after "goli", suggest commands',
    '    if [[ $COMP_CWORD -eq 1 ]]; then',
    '        COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )',
    '        return 0',
    '    fi',
    '',
    '    # Subcommand-specific flags',
    '    local cmd="${COMP_WORDS[1]}"',
    '    case "$cmd" in',
  ];

  for (const cmd of COMMANDS) {
    const flags = [...GLOBAL_FLAGS, ...cmd.flags];
    const flagStr = flags.map((f) => f.long).join(' ');
    lines.push(`        ${cmd.name})`);
    lines.push(`            opts="${flagStr}"`);
    lines.push(`            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )`);
    lines.push('            return 0');
    lines.push('            ;;');
  }

  lines.push('    esac');
  lines.push('');
  lines.push('    # Global flags (available for all commands)');
  lines.push('    local global_opts="' + GLOBAL_FLAGS.map((f) => f.long).join(' ') + '"');
  lines.push('    COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )');
  lines.push('    return 0');
  lines.push('}');
  lines.push('complete -F _goli goli');
  lines.push('');

  return lines.join('\n');
}

// ─── Zsh completion ───────────────────────────────────────────────────

function genZsh(): string {
  const lines: string[] = [
    '#compdef goli',
    '# goli zsh completion',
    '# Generated by scripts/gen-completions.ts — do not edit by hand.',
    '# Install: cp this file to ~/.zsh/completions/_goli && compinit',
    '',
    '_goli() {',
    '    local -a commands',
    '    commands=(',
  ];
  for (const cmd of COMMANDS) {
    lines.push(`        '${cmd.name}:${cmd.description.replace(/'/g, "'\\''")}'`);
  }
  lines.push('    )');
  lines.push('');
  lines.push('    _arguments -C \\');
  for (const f of GLOBAL_FLAGS) {
    const argPart = f.takesArg ? ':arg:' : '';
    const shortPart = f.short ? `'${f.short}[${f.description}]${argPart}' \\` : '';
    lines.push(`        '${f.long}[${f.description}]${argPart}' \\`);
    if (shortPart) lines.push(`        ${shortPart}`);
  }
  lines.push('        \'*: :->command\'');
  lines.push('');
  lines.push('    case $state in');
  lines.push('        command)');
  lines.push('            _describe \'command\' commands');
  lines.push('            ;;');
  lines.push('    esac');
  lines.push('}');
  lines.push('');
  lines.push('_goli "$@"');
  lines.push('');

  return lines.join('\n');
}

// ─── Fish completion ──────────────────────────────────────────────────

function genFish(): string {
  const lines: string[] = [
    '# goli fish completion',
    '# Generated by scripts/gen-completions.ts — do not edit by hand.',
    '# Install: cp this file to ~/.config/fish/completions/goli.fish',
    '',
    '# Commands',
  ];
  for (const cmd of COMMANDS) {
    lines.push(`complete -c goli -f -n '__fish_use_subcommand' -a '${cmd.name}' -d '${cmd.description.replace(/'/g, "\\'")}'`);
  }
  lines.push('');
  lines.push('# Global flags');
  for (const f of GLOBAL_FLAGS) {
    const argPart = f.takesArg ? ' -r' : '';
    lines.push(`complete -c goli -f -n '__fish_use_subcommand' -l '${f.long.replace(/^--/, '')}'${argPart} -d '${f.description.replace(/'/g, "\\'")}'`);
    if (f.short) {
      lines.push(`complete -c goli -f -n '__fish_use_subcommand' -s '${f.short.replace(/^-/, '')}'${argPart} -d '${f.description.replace(/'/g, "\\'")}'`);
    }
  }
  lines.push('');
  // Per-command flags
  for (const cmd of COMMANDS) {
    if (cmd.flags.length === 0) continue;
    lines.push(`# ${cmd.name} flags`);
    for (const f of cmd.flags) {
      const argPart = f.takesArg ? ' -r' : '';
      lines.push(`complete -c goli -f -n '__fish_seen_subcommand_from ${cmd.name}' -l '${f.long.replace(/^--/, '')}'${argPart} -d '${f.description.replace(/'/g, "\\'")}'`);
      if (f.short) {
        lines.push(`complete -c goli -f -n '__fish_seen_subcommand_from ${cmd.name}' -s '${f.short.replace(/^-/, '')}'${argPart} -d '${f.description.replace(/'/g, "\\'")}'`);
      }
    }
    lines.push('');
  }
  return lines.join('\n');
}

// ─── Main ─────────────────────────────────────────────────────────────

function main(): void {
  mkdirSync(OUTPUT_DIR, { recursive: true });

  const bash = genBash();
  const zsh = genZsh();
  const fish = genFish();

  writeFileSync(resolve(OUTPUT_DIR, 'goli.bash'), bash, 'utf-8');
  writeFileSync(resolve(OUTPUT_DIR, '_goli'), zsh, 'utf-8');  // zsh convention: underscore prefix
  writeFileSync(resolve(OUTPUT_DIR, 'goli.fish'), fish, 'utf-8');

  console.log(`✓ Generated completions in ${OUTPUT_DIR}:`);
  console.log('  goli.bash  (bash)');
  console.log('  _goli      (zsh)');
  console.log('  goli.fish  (fish)');
  console.log();
  console.log(`  ${GLOBAL_FLAGS.length} global flags, ${COMMANDS.length} commands, ${COMMANDS.reduce((s, c) => s + c.flags.length, 0)} command-specific flags`);
}

main();
