# goli bash completion
# Generated by scripts/gen-completions.ts — do not edit by hand.
# Install: source this file in your .bashrc, or copy to /etc/bash_completion.d/goli

_goli() {
    local cur prev opts cmds
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    # Top-level commands
    cmds="wakeup doctor status audit usage commit init mcp help"

    # If completing the first word after "goli", suggest commands
    if [[ $COMP_CWORD -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "$cmds" -- "$cur") )
        return 0
    fi

    # Subcommand-specific flags
    local cmd="${COMP_WORDS[1]}"
    case "$cmd" in
        wakeup)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help --interactive"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
        doctor)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
        status)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
        audit)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help --verbose --json"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
        usage)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
        commit)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
        init)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
        mcp)
            opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help"
            COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
            return 0
            ;;
    esac

    # Global flags (available for all commands)
    local global_opts="--version --print --debug --model --god --auto --sandbox --effort --output-format --spec-mode --diff-review --resume --branch --demo --help"
    COMPREPLY=( $(compgen -W "$global_opts" -- "$cur") )
    return 0
}
complete -F _goli goli
