# goli fish completion
# Generated by scripts/gen-completions.ts — do not edit by hand.
# Install: cp this file to ~/.config/fish/completions/goli.fish

# Commands
complete -c goli -f -n '__fish_use_subcommand' -a 'wakeup' -d 'Wake up the 11-agent swarm to perform a task'
complete -c goli -f -n '__fish_use_subcommand' -a 'doctor' -d 'Check system requirements and environment health'
complete -c goli -f -n '__fish_use_subcommand' -a 'status' -d 'Show health dashboard and active session stats'
complete -c goli -f -n '__fish_use_subcommand' -a 'audit' -d 'Verify safety audit log integrity'
complete -c goli -f -n '__fish_use_subcommand' -a 'usage' -d 'Show model usage and cost breakdown'
complete -c goli -f -n '__fish_use_subcommand' -a 'commit' -d 'Apply pending changes from a session to your host'
complete -c goli -f -n '__fish_use_subcommand' -a 'init' -d 'Initialize GOLI.md project memory and build the index'
complete -c goli -f -n '__fish_use_subcommand' -a 'mcp' -d 'Manage MCP (Model Context Protocol) servers'

# Global flags
complete -c goli -f -n '__fish_use_subcommand' -l 'version' -d 'Print version and exit'
complete -c goli -f -n '__fish_use_subcommand' -s 'V' -d 'Print version and exit'
complete -c goli -f -n '__fish_use_subcommand' -l 'print' -r -d 'Headless mode: run the agent, print the result to stdout, exit'
complete -c goli -f -n '__fish_use_subcommand' -s 'p' -r -d 'Headless mode: run the agent, print the result to stdout, exit'
complete -c goli -f -n '__fish_use_subcommand' -l 'debug' -d 'Enable debug logging'
complete -c goli -f -n '__fish_use_subcommand' -l 'model' -r -d 'Override the default model for this session'
complete -c goli -f -n '__fish_use_subcommand' -l 'god' -d 'Bypass ALL safety gates (USE WITH EXTREME CAUTION)'
complete -c goli -f -n '__fish_use_subcommand' -l 'auto' -d 'Auto-approve Tier 2 (Risky) actions'
complete -c goli -f -n '__fish_use_subcommand' -l 'sandbox' -r -d 'Override sandbox mode: read-only | workspace-write | danger-full-access'
complete -c goli -f -n '__fish_use_subcommand' -l 'effort' -r -d 'Override reasoning effort: low | high | max'
complete -c goli -f -n '__fish_use_subcommand' -l 'output-format' -r -d 'Headless output format: text | json | stream-json (default: text)'
complete -c goli -f -n '__fish_use_subcommand' -l 'spec-mode' -d 'Enable spec-driven mode — edit_file/write_file require an approved spec (H13)'
complete -c goli -f -n '__fish_use_subcommand' -l 'diff-review' -d 'Enable diff-first review in headless mode (H14)'
complete -c goli -f -n '__fish_use_subcommand' -l 'resume' -r -d 'Resume a previous session by ID (H16)'
complete -c goli -f -n '__fish_use_subcommand' -l 'branch' -r -d 'Branch a previous session by ID into a new session (H16)'
complete -c goli -f -n '__fish_use_subcommand' -l 'local-llms' -d 'Local-LLM three-axis router across local Ollama workers + cloud tier'
complete -c goli -f -n '__fish_use_subcommand' -l 'help' -d 'Print this help and exit'
complete -c goli -f -n '__fish_use_subcommand' -s 'h' -d 'Print this help and exit'

# wakeup flags
complete -c goli -f -n '__fish_seen_subcommand_from wakeup' -l 'interactive' -d 'Start the full Ink TUI for real-time chat (Phase 3)'
complete -c goli -f -n '__fish_seen_subcommand_from wakeup' -s 'i' -d 'Start the full Ink TUI for real-time chat (Phase 3)'

# audit flags
complete -c goli -f -n '__fish_seen_subcommand_from audit' -l 'verbose' -d 'Show recent entries'
complete -c goli -f -n '__fish_seen_subcommand_from audit' -s 'v' -d 'Show recent entries'
complete -c goli -f -n '__fish_seen_subcommand_from audit' -l 'json' -d 'Output as JSON (for CI / scripts)'
